### PR TITLE
Feature/sar 312 rollback

### PR DESCRIPTION
**Pull request by jmfadeley**
# Related Tickets

- [SAR-312](https://jira.amida-tech.com/browse/SAR-312)

# Other Repos' PR(s) Intended to Work With This PR

- LINK_TO_THE_PR or "None."

# How Things Worked (or Didn't) Before This PR

We were forked from `cql-execution`, now we're not.

# How Things Work Now (And How to Test)

Run `yarn test:nyc`. Ensure the checks below are good. Do a quick regression test, preferably against both `yarn localread` and `yarn start` to make sure everything works.

# Readiness

1. [ ] This PR passes all automated tests.
2. [ ] This PR has no linting errors.
3. [ ] This PR's changes to configuration files have been documented in all appropriate places (such as but not limited to README.md), if applicable.

### CODE REVIEW

**Review by anthem123 — APPROVED** [review]
Checked local and Kafka processors, both worked as expected. Approved

**Comment by hmayenve** [comment]
Hey @jmfadeley, Everything looks good except for one thing I noticed. When you run the tests `yarn test:nyc`, I noticed that one test fails because the measure name/path needs to be the same for both `.env` and `.env.test`. For example, for the `.env.test`, I had `CISE_HEDIS_MY2022` but for my `.env`, I had `DRRE_HEDIS_MY2022` and when I ran the tests, 1 test failed. I think that running the tests should completely be independent from the main app.

**Review by hmayenve — APPROVED** [review]
A jira ticket to handle the `Contract Kafka Processor Test` issue is being created therefore, im approving this pr because everything else looks good.

**Review by eawest2 — APPROVED** [review]
Gotta love hundreds of thousands of lines changed. 

Approved, merging and deleting.

**Pull request merged**
