### PR TITLE
Feature/sar 297 measurement member id and type

### PR DESCRIPTION
**Pull request by jmfadeley**
# Related Tickets

- [SAR-310](https://amida.atlassian.net/browse/SAR-310)
- [SAR-297](https://amida.atlassian.net/browse/SAR-297)
*Notice the changed `.env` variables.*

# Other Repos' PR(s) Intended to Work With This PR

`saraswati-hedis-results-api`. 

# How Things Worked (or Didn't) Before This PR

- We needed to update the NodeJS version in the Docker to 16+.
- We needed a devcontainer.
- We needed to modify the results returned to include `measurementType` and `memberId`.

# How Things Work Now (And How to Test)
I've updated the NodeJS version. Most of my testing against it was in the devcontainer which works great, which I recommend trying and using. You can run the regular (different) `Dockerfile` with...

`docker build -t saraswati-cql-execution .` 

Then...
`docker run --mount type=bind,source=<directory to>\private,target=/app/private -e MEASUREMENT_FILE=private/DRRE_HEDIS_MY2022-1.0.0/elm/DRRE_HEDIS_MY2022-1.0.0.json -e MEASUREMENT_TYPE=drre -e LIRARIES_DIRECTORY=private/DRRE_HEDIS_MY2022-1.0.0/libraryElm/ -e VALUESETS_DIRECTORY=private/DRRE_HEDIS_MY2022-1.0.0/valuesets/ -e KAFKA_BROKERS=["redpanda1:29092", "redpanda1:29093"] -e KAFKA_CONSUMED_TOPIC=fhir-logged -e KAFKA_PRODUCED_TOPIC=hedis-measures saraswati-cql-execution`

To test the output changes, you can manually run a reading through and verify that there are two new keys, or you can run the tests. If you do, be sure to change the following variables to this:

```
MEASUREMENT_FILE=private/DRRE_HEDIS_MY2022-1.0.0/elm/DRRE_HEDIS_MY2022-1.0.0.json
LIBRARIES_DIRECTORY=private/DRRE_HEDIS_MY2022-1.0.0/libraryElm/
VALUESETS_DIRECTORY=private/DRRE_HEDIS_MY2022-1.0.0/valuesets/
MEASUREMENT_TYPE=drre
```

Reason being, we only have the output contract for one reading for now. I could create readings for all of them, but there are better uses of our time...

### CODE REVIEW

**Review by anthem123 — COMMENTED** [review]
This isn't about something you have changed, but something you haven't changed.

`exec-config.js` line 148 there is a call to `removeArrayValues`. It does what it says which seems fine except for numerators/denominators that are arrays. This looks like the PR to remove it in.

**Comment by jmfadeley** [comment]
@anthem123 there. Please run `yarn test` to ensure it works on your end because that threw a few expectations for a loop.

**Comment by anthem123** [comment]
@jmfadeley I get one failed test, which makes sense. Removing that `removeArrayValues` method really changes the data that is returned. Do we need a list of all ValueSet codes sent to HeRA? Not sure, but it's good we are no longer removing the numerators and denominators.

**Review by anthem123 — APPROVED** [review]
LGTM, all data is now sent to HeRA

**Pull request merged**
